sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install: pip install tox
before_script:
- .travis/bump_version ./ ${AUTOVERSION_INCREMENT} > atlassian/VERSION
script:
- tox
deploy:
  provider: pypi
  user: cattz
  password:
    secure: sknkJzZo2XGshyCk/mnS/XTntd4LNuu92p9xYyF+kHtFU9vS2ImYB4qtAjPDkbgDDFGkwoQs7Ib0uzk1aj90ghJ90MzoAw9WMab6Jwvikr8Ul/cPgEtPG2hHz9zAA9S25s/0I2SGA4OUPSpew7W7Onuy2RIJvEU5piaqmRqQyidjYp6x54VSAKXP8fhoKClGyuwBR9nxzK/H6Eyjm7+Dcf5kG/myNT37vZ/JuoD6jvJ+HPmnz/B1GMDW3C5lolqCzQ1fJM53a/ioQKuua35EA1gU9K+9cMv6wtNlgZPGfSV4MaoJOQNmMXg7RaBXc2jUgMVSL28YqdgFn8kbL8FV7j8MIIMRnoy8fnpppDbIRKnaqP6NUo/nqIoWJ4z3rxzy8Y0QomGbCUaoEltIRKaeYclLG2t4drGPlGhys0snPDVNz7s1ID2mktOyKO1OcDZKjWyouJeG4zBcGMm0x5SBoq2oniZhxwkYJVafLlixPuFeO8HEP8+g7tUo9QDy2mOU7j3yc/qhP6lFMIS8HJ7j1H2DgBrdlf9CwvC5ElMdRjN3uBqsOZWKHk/HarS3suUGpkC6oGK0kMbBAHsYA9ValD8yOeBefw3nVCJSeuXhB0YzONuhvSJD1QBp/wQkOB5OXNSH8UGe2oWO5nJgQtOCI/50Ta7tRUXj+bcR4DN9ci4=
  distributions: sdist bdist_wheel
  on:
    branch: feature/travis_relase
    python: '3.6'
